baseurl = "https://broomburgo.github.io/fun-ios/"
disablePathToLower = false
languageCode = "en-us"
title = "Fun iOS"
theme = "hemingway"
copyright = "&copy; <a href=\"https://github.com/broomburgo\">Elviro Rocca</a> 2016"

# Number of blog posts displayed in each page
paginate = 6

# [permalinks]
# post = "/blog/:year-:month-:day-:title/" # change the post URL to look like the old ones

# Make tags and categories work
[indexes]
	tag = "tags"
	# category = "categories"

[params]

	# If false, all of the post will appear on front page (and in pagination)
	truncate = true

	# Author's name (this will appear in metadata and under posts)
	author = "Elviro Rocca"

	# This text appears in the site header under website title
	# subtitle = "Essays on iOS functional programming"

	# Used in the search engine
	# searchEngineURL = "https://www.google.com/search"

	# Text of the "Continue Reading" label. &rarr; == right arrow, but it gets messed up in the string so we will add it to index.html manually
	continueReadingText = "Read more"

  # # Google analytics code
  googleAnalytics = "UA-89456601-1"

	# Disqus shortcode
	# Disable comments for a specific post by adding "comments: false" in its frontmatter
	disqusShortname = "fun-ios"

	# rss = true  # switch to true to enable RSS icon link

  # Set to true to use a text label for RSS instead of an icon
  # This is overwritten by the `rss` setting
  # textrss = false

	# Website's default description
	defaultDescription = "Essays on iOS functional programming"

	# Populate this with your own search keywords - these will appear in the meta tags
	# defaultKeywords = ["keyword1" , "keyword2" , "keyword3" , "keyword4"]

  [params.highlight]
    style = "github"
    languages = ["swift"]

    [[params.social]]
      url = "https://github.com/broomburgo"
      fa_icon = "fa-github"

    [[params.social]]
      url = "https://twitter.com/_logicist"
      fa_icon = "fa-twitter"
